name: "setup-npm-env"
description: "Composite action to set up Node and install npm dependencies."

runs:
  using: "composite"
  steps:
    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Set up Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: 20
        cache: 'yarn'
        cache-dependency-path: ./hiero-wallet

    - name: Install dependencies
      run: cd ./hiero-wallet && yarn install --immutable
      shell: bash